Rancher integration updates
harvester/tests pull request #117
Opened 2021-11-24 23:22 UTC by noahgildersleeve

These are the tests that came out of the talks about Harvester Rancher integration. Also standardized test cases on non-spcific ordered lists in markdown.

2021-11-28 07:08 UTC, TachunLin reviewed
Test case `49-overprovision-harvester` file name mismatch with title `48-Verify Backup and restore on server migration`. This may cause duplicate test case name display on github page

Beside this, other cases looks good to me.
 
![image](https://user-images.githubusercontent.com/29251855/143733069-9b8c272f-3a6a-4a93-975d-cb7f5d8cee44.png)

2021-11-29 07:26 UTC, lanfon72 requested changes

2021-11-29 07:26 UTC, lanfon72 commented on docs/content/manual/harvester-rancher/49-overprovision-harvester.md
> +title: 48-Verify Backup and restore on server migration
title should be updated.

2021-11-29 07:26 UTC, lanfon72 commented on docs/content/manual/harvester-rancher/41-rancher-nested-harvester
> +---
file named without suffix `.md`

2021-11-29 17:56 UTC, noahgildersleeve commented on docs/content/manual/harvester-rancher/49-overprovision-harvester.md
> +title: 48-Verify Backup and restore on server migration
Changed.

2021-11-29 17:56 UTC, noahgildersleeve commented on docs/content/manual/harvester-rancher/41-rancher-nested-harvester
> +---
Changed.

2021-11-29 20:22 UTC, lanfon72 commented
LGTM

2021-11-29 20:24 UTC, lanfon72 approved these changes

2021-11-29 20:24 UTC, merged