Fix some automation issues found in v1.3.2 release testing
harvester/tests pull request #1489
Opened 2024-08-29 08:06 UTC by albinsun

#### Which issue(s) this PR fixes:

1. Issue #1464 

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-09-06 08:57 UTC, albinsun commented
Please help review, thx.

2024-09-06 18:44 UTC, irishgordo requested changes
just had a small qu for all new `# teardown` implmentations - otherwise non-blocking, will approve :smile:

2024-09-06 18:44 UTC, irishgordo commented on harvester_e2e_tests/integrations/test_5_vm_networks_interact.py
> +        vm_checker.wait_deleted(vm_name)
qu: For all `#teardown` new implementations -> do we want to pass in a wait_timeout for `wait_deleted` [from the virtualmachines.py fixture](https://github.com/harvester/tests/blob/586d6a718573a718f53ee3e7674fb0c647bf373f/harvester_e2e_tests/fixtures/virtualmachines.py#L224-L237) it's keyword arg of `endtime`?
Maybe something like `endtime=wait_timeout+datetime.now()` (pseudo code)

2024-09-08 18:42 UTC, lanfon72 approved these changes
LGTM

2024-09-09 23:25 UTC, irishgordo approved these changes

2024-09-10 00:10 UTC, merged