Cypress: Add cpu overcommit case
harvester/tests pull request #234
Opened 2022-03-14 10:58 UTC by n313893254

Manual test case: https://harvester.github.io/tests/manual/virtual-machines/cpu_overcommit/

2022-03-15 09:27 UTC, lanfon72 requested changes

2022-03-15 09:27 UTC, lanfon72 commented on cypress/testcases/virtualmachines/advanced.spec.ts
> +  it('Step 2: Check config', () => {
based on [the practice](https://docs.cypress.io/guides/references/best-practices#Having-tests-rely-on-the-state-of-previous-tests), _steps_ should be put in the same `specify / it` testing.

2022-03-15 09:27 UTC, lanfon72 commented on cypress/testcases/virtualmachines/cpu-overcommit.spec.ts
> +  it('Step2: Create VM && Check VM request', () => {
same problem as previous review

2022-03-16 02:34 UTC, n313893254 commented
@lanfon72 Done, thanks for your review. PTAL

2022-03-16 02:54 UTC, lanfon72 approved these changes
LGTM

2022-03-16 02:55 UTC, merged