e2e: FEAT Support Bundle For Failed Install
harvester/tests pull request #324
Opened 2022-04-29 02:04 UTC by irishgordo

* adding manual test documentation to cover manually testing a failed
  single node harvester iso install that will explain how to put the
  test environment in a given state to check that a support bundle gets
  generated upon iso single-node harvester install failure

  Resolves: feat/319-support-bundle-single-node-manual-test-doc
  
  This seems to work locally, ran make all, spun up `python3 -m http.server -d docs/public`:
 
![Screenshot from 2022-04-28 19-02-27](https://user-images.githubusercontent.com/5370752/165874707-4a848acd-c1dd-44be-bd8f-e9b7ecf22d45.png)

This relates to: https://github.com/harvester/harvester/issues/1864 primarily

2022-05-02 17:52 UTC, noahgildersleeve requested changes
It looks good, but new tests for features should go into the incoming tests folder with the ticket number in the name. The test looks good though.

2022-05-02 17:54 UTC, irishgordo commented
@noahgildersleeve awesome!  I'll make that edit and push up the changes :smile: - ty for reviewing this!

2022-05-06 19:36 UTC, irishgordo commented
Updated to put this in the `_incoming` folder with the harvester ticket number prepended at the front of the .md file-name and ran `make preview-hugo` (forgot there was a hook in the makefile to stand up hugo and manual test docs :sweat_smile:  - definitely cleaner than `python3 -m http.server`)

Super game to iterate or make any adjustments.  Pulled from main, so there shouldn't be any merge conflicts :smile: 

![Screenshot from 2022-05-06 12-33-44](https://user-images.githubusercontent.com/5370752/167205601-42109c8f-ef4c-4f5a-b8ea-6f65ba3f3786.png)

2022-05-06 20:19 UTC, noahgildersleeve approved these changes
LGTM

2022-05-06 20:19 UTC, merged