Cypress: Add Volume cases
harvester/tests pull request #331
Opened 2022-05-07 03:02 UTC by DaiYuzeng

#### Releated cases:
- https://harvester.github.io/tests/manual/volumes/create-image-from-volume/
- https://harvester.github.io/tests/manual/volumes/create-volume-root-disk-vm-image-form/
- https://harvester.github.io/tests/manual/volumes/create-volume-root-disk-vm-image-form-label/
- https://harvester.github.io/tests/manual/volumes/delete-volume-that-is-not-attached-to-vm/
- https://harvester.github.io/tests/manual/volumes/delete-volume-that-was-attached-to-vm-but-is-not-now/

2022-05-09 07:27 UTC, WuJun2016 commented on cypress/testcases/volumes.spec.ts
> + describe.only('Delete volume that was attached to VM but now is not', () => {
delete '.only'

2022-05-09 07:37 UTC, DaiYuzeng commented on cypress/testcases/volumes.spec.ts
> + describe.only('Delete volume that was attached to VM but now is not', () => {
done.

2022-05-31 14:00 UTC, noahgildersleeve commented
@DaiYuzeng This is marked as a draft PR. Is it ready for merging?

2022-06-06 06:12 UTC, DaiYuzeng commented
@noahgildersleeve Please take a look, thanks!

2022-06-09 09:46 UTC, TachunLin requested changes
Verified running volume.spec.ts test suite, some of the cases failed
Not sure it's related to network latency or dependency from other test

- [ ]  ***FAILED***  Create image from Volume
- [x]  ***PASS*** Create volume root disk VM Image Form
- [ ]  ***FAILED***  Delete volume that was attached to VM but now is not

![image](https://user-images.githubusercontent.com/29251855/172813953-be7e1026-54e4-4249-9802-b7d6057e7725.png)

* Create image from Volume failed in 
Found failure originate in 
[pageobjects/image.po.ts:128:43](https://192.168.0.131/__/#)
![image](https://user-images.githubusercontent.com/29251855/172815334-cea7a706-a81b-4f31-9ade-f5955f9870e9.png)

* `Delete volume that was attached to VM but now is not` failed in 
[pageobjects/volume.po.ts:90:12](https://192.168.0.131/__/#)
![image](https://user-images.githubusercontent.com/29251855/172816879-7c4855fd-fe14-4a5a-9bc8-f90131126303.png)

2022-07-07 07:17 UTC, n313893254 commented
Hi, @DaiYuzeng. The VM [PR](https://github.com/harvester/tests/pull/359) has merged, Please let me know if it caused any issues.

2022-07-07 07:22 UTC, DaiYuzeng commented
> Hi, @DaiYuzeng. The VM [PR](https://github.com/harvester/tests/pull/359) has merged, Please let me know if it caused any issues.

Thanks for the changes!
I am going to resolve the conflicts and then do some tests.
But I am working on an issue of Harvester Node Driver, I'll work on this issue 2/3 days later.

2022-11-01 08:51 UTC, DaiYuzeng commented on cypress/constants/constants.ts
> +    public dashboardUrl = '/harvester/c/local/harvesterhci.io.dashboard';
@WuJun2016 @n313893254 Please take a glimpse.

2022-11-01 08:54 UTC, DaiYuzeng commented on cypress/cypress.env.json.example
> +  "largeImage": {
And here

2022-11-01 08:55 UTC, DaiYuzeng commented on cypress/pageobjects/virtualmachine.po.ts
> +  public delete(namespace:string, name: string, { removeRootDisk }: { removeRootDisk?: boolean } = { removeRootDisk: true }) {
@WuJun2016 @n313893254 Please take a glimpse.

2022-11-01 08:56 UTC, DaiYuzeng commented on cypress/utils/components/checkbox.po.ts
> +    this.self().find('input').invoke('attr', 'value').then(isChecked => {
It seems like the selector `[role="checkbox"]` doesn't work.

2022-11-01 08:56 UTC, DaiYuzeng commented on cypress/utils/components/cru-resource.po.ts
> +  public footerButtons = '.cru-resource-footer'
Refator these members from private to public

2022-11-02 06:20 UTC, WuJun2016 requested changes

2022-11-03 09:25 UTC, DaiYuzeng commented
The PR is ready for review, please take a look, thanks!

2022-11-04 07:33 UTC, DaiYuzeng commented
@lanfon72 @TachunLin Hi! This PR is ready for review, please take a look, thanks!
The last case in image, the last case in volume and the first case in host can't be past, we'll fix these cases at incoming commit.

2022-11-07 10:42 UTC, TachunLin commented
* Tested can finish all **Image** test cases on Harvester `v1.1.0`, it takes 6 minutes 13 seconds execution time
![image](https://user-images.githubusercontent.com/29251855/200286762-bf24a607-8e59-4491-9eca-779dcdadcb3b.png)

* Tested can finish all **Volume** test cases on Harvester `v1.1.0`, it takes 3 minutes 15 seconds execution time
![image](https://user-images.githubusercontent.com/29251855/200289463-5267a153-d5f1-4e94-b9e8-e02b275acb33.png)

* Tested can finish all **Network** test cases on Harvester `v1.1.0`, it takes 1 minutes 6 seconds execution time
![image](https://user-images.githubusercontent.com/29251855/200290912-dc7acef3-1e9c-486e-bd6f-f56274e80dc3.png)

2022-11-07 13:59 UTC, TachunLin commented
1. To make the Image/`Create a ISO image via upload` works, we may need to change `/cypress/cypress/fixtures/cirros-0.5.2-aarch64-disk.img` to executable 
![image](https://user-images.githubusercontent.com/29251855/200328427-fe65c23b-9044-42ca-9896-ea3e3b8d1dbc.png)

2. We can use minio to setup as NFS backup target for the settings test cases

2022-11-08 02:22 UTC, DaiYuzeng commented
> While running the `hosts.spec.ts`, the 3rd test plan `Check Add disk` would failed at Line 70 `testcases/dashboard/hosts.spec.ts:70:8`
> 
> ![image](https://user-images.githubusercontent.com/29251855/200458613-4df34f39-2df1-4ca6-97f6-28d2d43bc8fc.png)

Hi @TachunLin ! We would like to file a new [issue](https://github.com/harvester/tests/issues/599) to track this failed case. Thanks!

2022-11-08 02:31 UTC, TachunLin approved these changes
According to above test result. 
Checked the related test cases can run correctly on Harvester v1.1.0 
For the hosts.spec.ts related issue would be track separately at test issue https://github.com/harvester/tests/issues/599

2022-11-08 05:00 UTC, DaiYuzeng commented
Hi @TachunLin ! The newest commit has been merged into this PR. It will affect two cases:

1. network
2. virtualmachine/network

![image](https://user-images.githubusercontent.com/15041915/200478965-6d5ed756-1160-42b0-914f-073fb69160b0.png)

Please take a look! Thanks! 

cc @n313893254 @WuJun2016

2022-11-08 07:42 UTC, TachunLin requested changes
@n313893254, @DaiYuzeng 
When tested the network/network.spec.ts, the Create Vlan1 and Vlan2 cases encounter failure. 
It would probably related to the column id changes. Please help to take a look. Thanks

* Create Vlan1 failed 
![image](https://user-images.githubusercontent.com/29251855/200493696-cb5e3fc7-2654-454b-9ce6-a07937967851.png)

* Create Vlan2 failed
![image](https://user-images.githubusercontent.com/29251855/200493783-3f75a42b-c42a-497b-9acd-1ed5393c01c2.png)

2022-11-08 10:22 UTC, TachunLin commented
Checked can pass the `Create Vlan1` and failed the `Create Vlan2`, it's correct behavior since Vlan 2 can routed on local kvm environment.  
![image](https://user-images.githubusercontent.com/29251855/200538952-c9308f6c-e710-4f11-99bc-25b4a0da4cf6.png)

Can pass all `virtualmachine/network` test cases
![image](https://user-images.githubusercontent.com/29251855/200539619-2da709e4-60a6-4556-83c0-56f23b6a2bec.png)

2022-11-08 18:01 UTC, noahgildersleeve commented
@WuJun2016 Could you check if your changes are still needed/fixed when you get a chance so we can get this merged?

2022-11-09 01:52 UTC, DaiYuzeng commented
Hi @noahgildersleeve @WuJun2016 ! I think this PR has been ready to merge, thank you!

2022-11-09 01:59 UTC, WuJun2016 commented
> Checked can pass the `Create Vlan1` and failed the `Create Vlan2`, it's correct behavior since Vlan 2 can't be routed on local kvm environment.

@noahgildersleeve   I think it can be merged. If there is any problem, we can submit a new pr to solve it.

2022-11-09 02:15 UTC, WuJun2016 approved these changes
LGTM, thanks

2022-11-09 07:00 UTC, n313893254 approved these changes

2022-11-09 15:55 UTC, merged