Included test for windows image Single VM and Multiple VM test
harvester/tests pull request #44
Opened 2021-08-25 15:04 UTC by yarunachalam

Included test for windows image Single VM and Multiple VM test

2021-08-30 22:44 UTC, guangyee approved these changes

2021-09-01 15:23 UTC, mbelur requested changes

2021-09-01 22:10 UTC, yarunachalam commented on harvester_e2e_tests/fixtures/image.py
>      url = ('http://10.84.144.252/meera/'
Done. Included in PR https://github.com/harvester/tests/pull/49
Closing this PR due to permission issue. I have to clone from my fork.

2021-09-01 22:10 UTC, yarunachalam commented
Closing this PR due to permission issue. I have to clone from my fork.
Created new PR #49

2021-09-01 22:10 UTC, closed without merging