Add test case for PVC creation in RKE2 cluster
harvester/tests pull request #764
Opened 2023-04-12 18:38 UTC by lanfon72

2023-04-13 17:04 UTC, lanfon72 commented
The new test case will depends on previous test case created RKE2 cluster.

2023-04-15 23:35 UTC, khushboo-rancher requested changes
Can we also check that relevant PV is created with correct info. I understand that if the PVC's status is `bound` that means the PV is created successfully but as a part of testing we should also check the PV's details.

2023-04-15 23:35 UTC, khushboo-rancher commented on harvester_e2e_tests/integration/test_rancher_integration.py
> +            if "Bound" == data['status'].get('phase'):
Can you also add a check for having the right storage class and size?

2023-04-17 18:36 UTC, khushboo-rancher commented on apiclient/rancher_api/cluster_models.py
> +    def mode_rwm(self):
nit: rwx is general acronym for Read write many.

2023-04-17 18:36 UTC, khushboo-rancher approved these changes

2023-04-17 18:38 UTC, khushboo-rancher commented
Thanks @lanfon72, merging this now, you can address [this](https://github.com/harvester/tests/pull/764#discussion_r1169132453) later.

2023-04-17 18:38 UTC, merged